<?php
include_once 'admin/includes/functions.php';
?>

<style type="text/css">
	/* Forces the background container to hold color and height on active scrolling */
	.horizontal-main,
	.sticky-wrapper.is-sticky .horizontal-main,
	.fixed-header .horizontal-main {
		background-color: #f5f6f8 !important;
		border-bottom: 4px solid #e72a1a !important;
		box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05) !important;
		height: auto !important;
		min-height: auto !important;
		padding: 0 !important;
	}

	/* Target sticky containers generated by third-party plugins */
	.sticky-wrapper,
	.sticky-wrapper.is-sticky {
		height: auto !important;
		background: transparent !important;
		position: static !important;
		z-index: auto !important;
	}

	/* header-main is now sticky via ux-enhancements.css */
	.header-main {
		z-index: 1050 !important;
	}

	.horizontal-main,
	.horizontal-header,
	.sticky-wrapper,
	.sticky-wrapper.is-sticky {
		height: auto !important;
	}

	/* Mobile-only top strip — hide on desktop */
	.horizontal-header {
		background-color: #ffffff !important;
		border-bottom: 2px solid #e72a1a !important;
		display: flex !important;
		/* visible on mobile by default */
	}

	/* Hide mobile strip on desktop, show desktop nav */
	@media (min-width: 992px) {
		.horizontal-header {
			display: none !important;
		}
	}

	/* Hide desktop nav on mobile (shown by the horizontal menu plugin) */
	@media (max-width: 991px) {
		.horizontal-main {
			display: none !important;
		}

		/* But show it when menu is toggled open */
		.horizontalMenu.menuopen~.horizontal-main,
		body.nav-open .horizontal-main {
			display: block !important;
		}
	}


	.horizontal-header .animated-arrow span,
	.horizontal-header .animated-arrow span:before,
	.horizontal-header .animated-arrow span:after {
		background: #1e1e1e !important;
	}

	.horizontal-header .callusbtn i {
		color: #1e1e1e !important;
	}

	/* Floating Social Buttons */
	.float {
		position: fixed;
		width: 60px;
		height: 60px;
		bottom: 20px;
		right: 40px;
		background-color: #25d366;
		color: #FFF;
		border-radius: 50px;
		text-align: center;
		font-size: 30px;
		box-shadow: 2px 2px 3px #999;
		z-index: 9999;
	}

	.float2 {
		position: fixed;
		width: 60px;
		height: 60px;
		bottom: 20px;
		right: 115px;
		background-color: #1877f2;
		/* Fixed to official Facebook Blue */
		color: #FFF;
		border-radius: 50px;
		text-align: center;
		font-size: 30px;
		box-shadow: 2px 2px 3px #999;
		z-index: 9999;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.my-float {
		margin-top: 16px;
	}

	.float2 img {
		width: 32px;
		height: 32px;
		object-fit: contain;
	}

	/* Mobile Mega Menu Specific Fixes */
	@media (max-width: 991px) {
		.horizontal-megamenu {
			width: 100% !important;
			padding: 15px !important;
			box-sizing: border-box;
			background-color: #fff !important;
		}

		.horizontal-megamenu .row {
			display: flex !important;
			flex-direction: column !important;
			margin: 0 !important;
			padding: 0 !important;
		}

		.horizontal-megamenu .link-list {
			width: 100% !important;
			flex: 0 0 100% !important;
			max-width: 100% !important;
			margin-bottom: 20px !important;
			padding: 0 !important;
			list-style: none;
		}

		.horizontal-megamenu .link-list .title {
			background-color: #f0f2f5;
			padding: 8px 10px !important;
			font-weight: bold;
			color: #e72a1a !important;
			margin-top: 5px !important;
			margin-bottom: 5px !important;
		}

		.horizontal-megamenu .link-list li a {
			padding: 8px 15px !important;
			display: block !important;
			border-bottom: 1px solid #eee;
			color: #333 !important;
		}
	}

	/* Desktop Media Queries */
	@media (min-width: 992px) {

		.horizontal-mainwrapper,
		.sticky-wrapper.is-sticky .horizontal-mainwrapper,
		.fixed-header .horizontal-mainwrapper {
			display: flex !important;
			align-items: center !important;
			justify-content: space-between !important;
			width: 100% !important;
			max-width: 100% !important;
			margin: 0 auto !important;
			padding: 12px 40px !important;
			float: none !important;
			height: auto !important;
		}

		.desktoplogo,
		.desktoplogo-1 {
			float: none !important;
			padding: 0 !important;
			margin: 0 !important;
			flex-shrink: 0 !important;
		}

		.desktoplogo img,
		.desktoplogo-1 img {
			width: auto !important;
			max-height: 45px !important;
			margin-top: 0 !important;
		}

		.horizontalMenu {
			float: none !important;
			margin: 0 !important;
			padding: 0 !important;
			flex-grow: 1 !important;
			display: flex !important;
			align-items: center !important;
			justify-content: flex-start !important;
			margin-left: 40px !important;
		}

		.horizontalMenu-list {
			display: flex !important;
			align-items: center !important;
			list-style: none !important;
			margin: 0 !important;
			padding: 0 !important;
			width: auto !important;
		}

		.horizontalMenu-list>li {
			float: none !important;
			padding: 0 !important;
			margin: 0 !important;
		}

		.horizontalMenu>.horizontalMenu-list>li>a {
			color: #1e1e1e !important;
			font-family: 'Arial', 'Helvetica', sans-serif !important;
			font-size: 15px !important;
			text-transform: none !important;
			font-weight: 600 !important;
			letter-spacing: 0px !important;
			padding: 10px 18px !important;
			transition: color 0.2s ease !important;
			background: transparent !important;
		}

		.horizontalMenu>.horizontalMenu-list>li:hover>a,
		.horizontalMenu>.horizontalMenu-list>li>a:hover,
		.horizontalMenu>.horizontalMenu-list>li>a.active {
			background: transparent !important;
			color: #1e1e1e !important;
			text-decoration: solid 2px underline #e72a1a !important;
		}

		.horizontalMenu>.horizontalMenu-list>li:hover>a .fa,
		.horizontalMenu>.horizontalMenu-list>li>a:hover .fa,
		.horizontalMenu>.horizontalMenu-list>li>a.active .fa {
			background-color: transparent !important;
			color: #1e1e1e !important;
		}

		.horizontalMenu>ul.mb-0 {
			margin-bottom: 0 !important;
			padding-left: 0 !important;
			list-style: none !important;
			display: flex !important;
			align-items: center !important;
		}

		.horizontalMenu>ul.mb-0>li {
			padding: 0 !important;
			margin: 0 !important;
			margin-left: 10px !important;
		}

		.horizontalMenu>ul.mb-0>li>span>a.ad-post {
			margin: 0 !important;
			padding: 8px 18px !important;
			font-size: 13px !important;
			font-family: 'Arial', sans-serif !important;
			text-transform: uppercase !important;
			border-radius: 0px !important;
			font-weight: 500 !important;
			background-color: #28a745 !important;
			border-color: #28a745 !important;
		}

		.horizontalMenu>ul.mb-0>li>span>a.ad-post:hover {
			background-color: #218838 !important;
			border-color: #1e7e34 !important;
		}

		.horizontalMenu>.horizontalMenu-list>li>.horizontal-megamenu {
			top: 100% !important;
			margin-top: 0px !important;
		}

		.horizontalMenu>.horizontalMenu-list>li[aria-haspopup="true"]>a::after {
			content: "" !important;
			position: absolute !important;
			bottom: -40px !important;
			left: 0 !important;
			right: 0 !important;
			height: 40px !important;
			background: transparent !important;
			display: block !important;
			z-index: 10 !important;
		}

		.pickup-header-search {
			display: flex !important;
			align-items: center !important;
			margin-left: auto !important;
			flex-shrink: 0 !important;
		}

		.pickup-search-box {
			position: relative !important;
			display: flex !important;
			align-items: center !important;
			border: 1px solid #ccc !important;
			background: #fff !important;
			width: 500px !important;
			max-width: 100% !important;
			height: 42px !important;
			overflow: hidden !important;
			margin-top: 5px;
			margin-bottom: 5px;
		}

		.pickup-search-box input[type=text] {
			width: 100% !important;
			height: 100% !important;
			border: none !important;
			padding: 8px 60px 8px 15px !important;
			font-size: 16px !important;
		}

		.pickup-search-box input[type="text"]::placeholder {
			color: #9ea8b6 !important;
			font-weight: normal !important;
		}

		.pickup-search-box input[type="text"]:focus {
			outline: none !important;
			box-shadow: none !important;
		}

		.pickup-search-box .search-btn {
			position: absolute !important;
			right: 0 !important;
			top: 0 !important;
			height: 100% !important;
			width: 60px !important;
			border: none !important;
			border-left: 1px solid #cccccc !important;
			background-color: transparent !important;
			color: #555 !important;
			cursor: pointer !important;
			display: flex !important;
			align-items: center !important;
			justify-content: center !important;
			transition: all .2s ease !important;
		}

		.pickup-search-box .search-btn i {
			font-size: 22px !important;
		}

		.pickup-search-box .search-btn:hover {
			background-color: #f7f7f7 !important;
			color: #e72a1a !important;
		}
	}

	/* Mobile Search Styles */
	.pickup-search-box-mobile {
		position: relative !important;
		display: flex !important;
		align-items: center !important;
		border: 1px solid #dcdcdc !important;
		border-radius: 0px !important;
		background-color: #ffffff !important;
		width: 100% !important;
		height: 38px !important;
		overflow: hidden !important;
	}

	.pickup-search-box-mobile input[type="text"] {
		border: none !important;
		padding: 8px 45px 8px 15px !important;
		width: 100% !important;
		height: 100% !important;
		font-size: 11px !important;
		font-family: 'Roboto', sans-serif !important;
		color: #333333 !important;
		font-weight: bold !important;
		background: transparent !important;
		text-transform: uppercase !important;
	}

	.pickup-search-box-mobile input[type="text"]::placeholder {
		color: #9ea8b6 !important;
		font-weight: bold !important;
	}

	.pickup-search-box-mobile .search-btn {
		position: absolute !important;
		right: 0 !important;
		top: 0 !important;
		height: 100% !important;
		width: 45px !important;
		border: none !important;
		border-left: 1px solid #dcdcdc !important;
		background-color: transparent !important;
		color: #7b8a9e !important;
		cursor: pointer !important;
		display: flex !important;
		align-items: center !important;
		justify-content: center !important;
	}

	/* =========================================
   Responsive Header Search
========================================= */

	@media (max-width:1400px) {

		.pickup-search-box {
			width: 420px !important;
		}

		.pickup-search-box input {
			font-size: 15px !important;
		}

		.horizontalMenu>.horizontalMenu-list>li>a {
			font-size: 14px !important;
			padding: 10px 14px !important;
		}

	}

	@media (max-width:1200px) {

		.pickup-search-box {
			width: 340px !important;
			height: 46px !important;
		}

		.pickup-search-box input {
			font-size: 14px !important;
		}

		.pickup-search-box .search-btn {
			width: 54px !important;
		}

		.pickup-search-box .search-btn i {
			font-size: 20px !important;
		}

		.horizontalMenu>.horizontalMenu-list>li>a {
			font-size: 13px !important;
			padding: 8px 12px !important;
		}

	}

	@media (max-width:1050px) {

		.pickup-search-box {
			width: 280px !important;
			height: 42px !important;
		}

		.pickup-search-box input {
			font-size: 13px !important;
			padding-left: 12px !important;
		}

		.pickup-search-box .search-btn {
			width: 48px !important;
		}

		.pickup-search-box .search-btn i {
			font-size: 18px !important;
		}

		.horizontalMenu>.horizontalMenu-list>li>a {
			font-size: 12px !important;
			padding: 8px 10px !important;
		}

	}
</style>

<body>

	<a href="https://api.whatsapp.com/send?phone=+81 80-7235-1820&text=Hi..!." class="float" target="_blank">
		<i class="fa fa-whatsapp my-float"></i>
	</a>
	<a href="https://web.facebook.com/HTCjapan/" class="float2" title="Get in touch on Facebook" target="_blank">
		<img id="fb_msg_icon"
			src="http://store-images.s-microsoft.com/image/apps.7488.13510798886918977.69182166-f125-495d-80d2-44fdaab21523.8fcea13e-5d9a-48a9-9937-b26deeced1b5"
			alt="Facebook">
	</a>

	<div class="header-main">
		<div class="horizontal-header clearfix">
			<div class="container">
				<a id="horizontal-navtoggle" class="animated-arrow"><span></span></a>
				<span class="smllogo"><img src="admin/img/logo/<?= $company_logo ?>" width="50" alt="" /></span>
				<a href="tel:<?= $company_company_phone ?>" class="callusbtn"><i class="fa fa-phone"
						aria-hidden="true"></i></a>
			</div>
		</div>
		<div class="horizontal-main clearfix">
			<div class="horizontal-mainwrapper container clearfix">
				<div class="desktoplogo">
					<a href="index.php"><img style="width: 100px;margin-top: -10px;"
							src="admin/img/logo/<?= $company_logo ?>" alt=""></a>
				</div>
				<div class="desktoplogo-1">
					<a href="index.php"><img style="width: 100px;margin-top: -10px;"
							src="admin/img/logo/<?= $company_logo ?>" alt=""></a>
				</div>
				<nav class="horizontalMenu clearfix d-md-flex">
					<ul class="horizontalMenu-list">
						<li class="d-lg-none mobile-search-item"
							style="padding: 15px 20px; border-bottom: 1px solid #eee; width: 100%;">
							<form action="advancesearch.php" method="get">
								<input type="hidden" name="advance" value="s">
								<div class="pickup-search-box-mobile">
									<input type="text" name="stockid" placeholder="ENTER STOCK ID" required>
									<button type="submit" class="search-btn">
										<i class="fa fa-search"></i>
									</button>
								</div>
							</form>
						</li>
						<li aria-haspopup="true"><a href="index.php">Home</a></li>
						<li aria-haspopup="true"><a href="advancesearch.php?type=stock">Vehicles <span
									class="fa fa-caret-down m-0"></span></a>
							<div class="horizontal-megamenu clearfix">
								<div class="container">
									<div class="megamenu-content">
										<div class="row">
											<ul class="col link-list">
												<li class="title">Makers</li>
												<?php $q = get($dbc, "maker WHERE maker_sts = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&maker=<?= $r['maker_id'] ?>"><?= $r['maker_name'] ?></a>
													</li>
												<?php endwhile ?>
											</ul>
											<ul class="col link-list">
												<li class="title">Brands</li>
												<?php $q = get($dbc, "brands WHERE brand_status = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&brands=<?= $r['brand_id'] ?>"><?= $r['brand_name'] ?></a>
													</li>
												<?php endwhile ?>
											</ul>
											<ul class="col link-list">
												<li class="title">Body Type</li>
												<?php $q = get($dbc, "body_type WHERE body_type_sts = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&body_type=<?= $r['body_type_id'] ?>"><?= $r['body_type_name'] ?></a>
													</li>
												<?php endwhile ?>
											</ul>
											<ul class="col link-list">
												<li class="title">Transmission</li>
												<?php $q = get($dbc, "transmission WHERE transmission_sts = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&transmission=<?= $r['transmission_name'] ?>"><?= $r['transmission_name'] ?></a>
													</li>
												<?php endwhile ?>
												<li class="title mt-4">Steering</li>
												<?php $q = get($dbc, "options WHERE option_sts = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&options=<?= $r['option_name'] ?>"><?= $r['option_name'] ?></a>
													</li>
												<?php endwhile ?>
											</ul>
											<ul class="col link-list">
												<li class="title">Drive</li>
												<?php $q = get($dbc, "drive WHERE drive_sts = '1' LIMIT 10");
												while ($r = mysqli_fetch_assoc($q)): ?>
													<li><a
															href="advancesearch.php?advance=s&drive=<?= $r['drive_name'] ?>"><?= $r['drive_name'] ?></a>
													</li>
												<?php endwhile ?>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</li>
						<li aria-haspopup="true"><a href="part-list.php"> Parts</a></li>
						<li aria-haspopup="true"><a href="machines-list.php"> Machines</a></li>
						<li aria-haspopup="true"><a href="about.php">About Us</a></li>
						<li aria-haspopup="true"><a href="howto.php">How To Buy</a></li>
					</ul>
				</nav>
				<div class="pickup-header-search d-none d-lg-block">
					<form action="advancesearch.php" method="get">
						<input type="hidden" name="advance" value="s">
						<div class="pickup-search-box">
							<input type="text" name="stockid" placeholder="ENTER STOCK ID" required>
							<button type="submit" class="search-btn">
								<i class="fa fa-search"></i>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>